---
title: "Reproducible Research: Peer Assessment 1"
author: "Enlik Tjioe"
output: 
  html_document:
    keep_md: true
---


## Library
```{r}
library(ggplot2)
library(lubridate)
```


## Loading and preprocessing the data
```{r}

data1 <- read.csv(unz("activity.zip", "activity.csv"))
str(data1)

data1$date <- ymd(data1$date)
```


## What is mean total number of steps taken per day?
```{r}
totalSteps <- aggregate (steps ~ date, data = data1, FUN = sum, na.rm=TRUE)

#Make a histogram of the total number of steps taken each day
hist(totalSteps$steps, xlab = "Steps", main = "Steps / Day", breaks = 10, col = "blue")
```
```{r}
#Calculate and report the mean and median total number of steps taken per day
mean(totalSteps$steps)
median(totalSteps$step)
```
Mean = 10766.19 steps
Median = 10765 steps



## What is the average daily activity pattern?

```{r}
# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
stepsInterval <- aggregate(steps ~ interval, data1, mean)
plot(stepsInterval$interval, stepsInterval$steps, type = "l", xlab = "5-minutes Interval", ylab = "Average Steps", main = "Average Daily Activity Pattern", col = "orange")
```

```{r}
# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
stepsInterval$interval[which.max(stepsInterval$steps)]
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
